//! `loop diagram` — the machine as a mermaid `stateDiagram-v2`.
//!
//! Pure over the IR: same machine in, same bytes out, no filesystem, no VM.
//!
//! What it draws is the graph the engine will actually walk, which is *not*
//! the `:transitions` list. An `:on-fail {:route ...}` commits a real
//! transition too (`validate` counts one as a loop head's re-entry for exactly
//! that reason), and in the shipped `standard-ticket` template the back-edges
//! exist *only* that way — a diagram of the declared edges alone would render
//! it as a straight line and quietly lie about the machine's shape.
//!
//! The edge labels are guard *shapes*, not guard text. A `:criteria` is a
//! paragraph of prose; pasting it onto an arrow makes an unreadable picture,
//! and the picture is the point. Read the machine file for the wording.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::core::text::one_line;
use crate::core::{LoopSpec, Machine, OnExhausted, OnFail, Transition};

/// Render `machine` as a mermaid `stateDiagram-v2` document, newline-terminated.
pub fn mermaid(machine: &Machine) -> String {
    let ids = NodeIds::new(machine);
    let mut out = String::new();

    // A frontmatter title is the only way a mermaid diagram names itself, and
    // a diagram pasted into a PR should say which ticket it is.
    let _ = writeln!(out, "---\ntitle: \"{}\"\n---", label(&machine.ticket));
    out.push_str("stateDiagram-v2\n");
    // File name, not the full path: a rendered diagram gets checked in and
    // pasted around, and nobody else's repo wants somebody's `$HOME` in it.
    let source = machine
        .source_path
        .file_name()
        .unwrap_or(machine.source_path.as_os_str());
    let _ = writeln!(
        out,
        "    %% generated by `loop diagram` from {}",
        label(&source.to_string_lossy())
    );

    // A node needs a declaration line only when its label differs from the
    // alias mermaid will print — i.e. when the id had to be sanitized, or when
    // it carries an annotation.
    out.push('\n');
    for (name, alias) in &ids.map {
        let mut text = (*name).to_string();
        if machine.escalation_state.as_deref() == Some(*name) {
            text.push_str(" (escalation)");
        }
        let text = label(&text);
        if text != *alias {
            let _ = writeln!(out, "    state \"{text}\" as {alias}");
        }
    }

    let _ = writeln!(out, "\n    [*] --> {}", ids.get(&machine.entry));

    // Declaration order: the machine file's own reading order.
    let mut routes: BTreeSet<(&str, &str)> = BTreeSet::new();
    for t in &machine.transitions {
        let _ = writeln!(
            out,
            "    {} --> {} : {}",
            ids.get(&t.from),
            ids.get(&t.to),
            edge_label(t)
        );
        if let OnFail::Route(target) = &t.on_fail {
            routes.insert((t.from.as_str(), target.as_str()));
        }
    }
    if !routes.is_empty() {
        out.push_str("\n    %% back-edges taken when a guard fails (`:on-fail {:route ...}`)\n");
        for (from, to) in routes {
            let _ = writeln!(
                out,
                "    {} --> {} : guard fails",
                ids.get(from),
                ids.get(to)
            );
        }
    }

    if !machine.terminals.is_empty() {
        out.push('\n');
        for t in &machine.terminals {
            let _ = writeln!(out, "    {} --> [*]", ids.get(t));
        }
    }

    // Loops overlap — in the worked example `qa-staging` heads one and belongs
    // to another — so they cannot be composite states. One note per head,
    // listing every loop that starts there.
    let mut by_head: BTreeMap<&str, Vec<&LoopSpec>> = BTreeMap::new();
    for l in &machine.loops {
        if let Some(head) = l.head() {
            by_head.entry(head.as_str()).or_default().push(l);
        }
    }
    for (head, loops) in by_head {
        let _ = writeln!(out, "\n    note right of {}", ids.get(head));
        for l in loops {
            let _ = writeln!(
                out,
                "        loop \"{}\": max {} cycles, then {}",
                label(&l.name),
                l.max_cycles,
                exhausted(machine, l)
            );
        }
        out.push_str("    end note\n");
    }

    out
}

/// What an edge is gated on, in the fewest words that still distinguish the
/// tiers: `check` is the harness's own subprocess, `judge` is the LLM.
fn edge_label(t: &Transition) -> String {
    let mut parts: Vec<String> = Vec::new();
    if t.check.is_some() {
        parts.push("check".into());
    }
    if t.criteria.is_some() {
        parts.push("judge".into());
    }
    // Worth naming: an unguarded edge commits the worker's proposal unexamined,
    // and `validate` warns about it. The diagram should show the same hole.
    if parts.is_empty() {
        parts.push("unguarded".into());
    }
    if let Some(s) = t.backoff_s {
        parts.push(format!("wait {s}s"));
    }
    // `retry` is the default and would be noise on every arrow; a `route` gets
    // its own arrow further down. Only `abort` needs saying here.
    if matches!(t.on_fail, OnFail::Abort) {
        parts.push("abort on fail".into());
    }
    parts.join(", ")
}

fn exhausted(machine: &Machine, l: &LoopSpec) -> String {
    match l.on_exhausted {
        OnExhausted::Abort => "abort".into(),
        OnExhausted::Escalate => match &machine.escalation_state {
            Some(e) => format!("escalate to {}", label(e)),
            None => "escalate".into(),
        },
    }
}

/// Every id in the machine, mapped to a mermaid-safe node alias.
struct NodeIds<'a> {
    map: BTreeMap<&'a str, String>,
}

impl<'a> NodeIds<'a> {
    fn new(machine: &'a Machine) -> Self {
        let mut names: BTreeSet<&str> = BTreeSet::new();
        names.extend(machine.states.keys().map(String::as_str));
        names.extend(machine.terminals.iter().map(String::as_str));
        names.insert(machine.entry.as_str());
        for t in &machine.transitions {
            names.insert(t.from.as_str());
            names.insert(t.to.as_str());
            if let OnFail::Route(target) = &t.on_fail {
                names.insert(target.as_str());
            }
        }
        for l in &machine.loops {
            names.extend(l.states.iter().map(String::as_str));
        }

        let mut map = BTreeMap::new();
        let mut taken: BTreeSet<String> = BTreeSet::new();
        for name in names {
            let base = sanitize(name);
            let mut alias = base.clone();
            let mut n = 2;
            while !taken.insert(alias.clone()) {
                alias = format!("{base}_{n}");
                n += 1;
            }
            map.insert(name, alias);
        }
        Self { map }
    }

    /// The alias for `name`. Every id reachable from the machine was collected
    /// in `new`, so the fallback only fires on a caller passing something the
    /// machine never mentioned.
    fn get(&self, name: &str) -> &str {
        self.map.get(name).map_or("_unknown", String::as_str)
    }
}

/// Mermaid node ids are bare words: `qa-staging --> debug` would be read as
/// part of the arrow. Each id gets an ASCII-safe alias, and its real name comes
/// back as the node's display label.
fn sanitize(id: &str) -> String {
    let mut out: String = id
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if !out.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_') {
        out.insert(0, '_');
    }
    out
}

/// Labels run to end-of-line and are delimited by `"`, so a newline or a quote
/// in an id would break the parse rather than look ugly.
///
/// The quote half is mermaid's alone; the flattening is
/// [`crate::core::text::one_line`], shared with every other place that has to fit
/// somebody else's text into one row.
fn label(s: &str) -> String {
    one_line(s).replace('"', "'")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::{Check, OnExhausted};
    use crate::engine::test_support::*;

    /// The shipped template's shape: a spine of judged edges whose back-edges
    /// exist only as `on_fail: route`. If those are dropped the picture is a
    /// straight line, which is the whole reason this module draws them.
    #[test]
    fn on_fail_routes_are_drawn_as_edges() {
        let mut m = base_machine();
        m.entry = "implement".into();
        m.terminals = ["done"].iter().map(|s| s.to_string()).collect();
        for id in ["implement", "review"] {
            m.states.insert(id.into(), state(id));
        }
        m.transitions = vec![
            judged_edge("implement", "review", "plan is addressed"),
            Transition {
                on_fail: OnFail::Route("implement".into()),
                ..judged_edge("review", "done", "no blocking defects")
            },
        ];

        let out = mermaid(&m);
        assert!(out.contains("implement --> review : judge"), "{out}");
        assert!(out.contains("review --> done : judge"), "{out}");
        assert!(
            out.contains("review --> implement : guard fails"),
            "the route back-edge must be drawn: {out}"
        );
        assert!(out.contains("[*] --> implement"), "{out}");
        assert!(out.contains("done --> [*]"), "{out}");
    }

    /// Hyphenated ids are the norm in the example machines, and they collide
    /// with mermaid's arrow token. The alias carries the graph; the label
    /// carries the real name.
    #[test]
    fn hyphenated_ids_are_aliased_and_still_labelled_with_the_real_name() {
        let mut m = base_machine();
        m.entry = "qa-staging".into();
        m.terminals = ["done"].iter().map(|s| s.to_string()).collect();
        m.states.insert("qa-staging".into(), state("qa-staging"));
        m.transitions = vec![edge("qa-staging", "done")];

        let out = mermaid(&m);
        assert!(out.contains("state \"qa-staging\" as qa_staging"), "{out}");
        assert!(out.contains("qa_staging --> done"), "{out}");
        assert!(!out.contains("qa-staging -->"), "{out}");
    }

    /// Two ids that sanitize to the same alias must not become one node.
    #[test]
    fn colliding_aliases_stay_distinct_nodes() {
        let mut m = base_machine();
        m.entry = "qa-staging".into();
        m.terminals = ["done"].iter().map(|s| s.to_string()).collect();
        for id in ["qa-staging", "qa_staging"] {
            m.states.insert(id.into(), state(id));
        }
        m.transitions = vec![edge("qa-staging", "qa_staging"), edge("qa_staging", "done")];

        let out = mermaid(&m);
        assert!(out.contains("qa_staging --> qa_staging_2"), "{out}");
        assert!(out.contains("qa_staging_2 --> done"), "{out}");
    }

    /// Each guard tier gets its own token, and a bare edge says so — the
    /// picture should show the same hole `validate` warns about.
    #[test]
    fn edge_labels_name_the_guard_tiers() {
        let both = Transition {
            check: Some(Check::new("cargo test")),
            ..judged_edge("a", "b", "it works")
        };
        assert_eq!(edge_label(&both), "check, judge");
        assert_eq!(edge_label(&checked_edge("a", "b", "true")), "check");
        assert_eq!(edge_label(&judged_edge("a", "b", "x")), "judge");
        assert_eq!(edge_label(&edge("a", "b")), "unguarded");

        let transient = Transition {
            backoff_s: Some(30),
            on_fail: OnFail::Abort,
            ..checked_edge("qa", "qa", "classify.sh")
        };
        assert_eq!(edge_label(&transient), "check, wait 30s, abort on fail");
    }

    /// Overlapping loops can't be composite states, so they share one note on
    /// their head — and `escalate` names where it escalates to.
    #[test]
    fn overlapping_loops_share_a_note_on_their_head() {
        let mut m = base_machine();
        m.entry = "qa".into();
        m.terminals = ["done", "blocked"].iter().map(|s| s.to_string()).collect();
        m.escalation_state = Some("blocked".into());
        for id in ["qa", "debug"] {
            m.states.insert(id.into(), state(id));
        }
        m.transitions = vec![edge("qa", "debug"), edge("debug", "qa"), edge("qa", "done")];
        m.loops = vec![
            loop_spec("qa", &["qa", "debug"], 4, OnExhausted::Escalate),
            loop_spec("qa-transient", &["qa"], 3, OnExhausted::Abort),
        ];

        let out = mermaid(&m);
        assert!(out.contains("note right of qa\n"), "{out}");
        assert_eq!(
            out.matches("end note").count(),
            1,
            "one note, not two: {out}"
        );
        assert!(
            out.contains("loop \"qa\": max 4 cycles, then escalate to blocked"),
            "{out}"
        );
        assert!(
            out.contains("loop \"qa-transient\": max 3 cycles, then abort"),
            "{out}"
        );
        assert!(
            out.contains("state \"blocked (escalation)\" as blocked"),
            "{out}"
        );
    }

    /// Same machine, same bytes — the output is checked into repos and diffed.
    #[test]
    fn output_is_deterministic() {
        let mut m = base_machine();
        m.entry = "implement".into();
        m.terminals = ["done"].iter().map(|s| s.to_string()).collect();
        m.states.insert("implement".into(), state("implement"));
        m.transitions = vec![judged_edge("implement", "done", "shipped")];
        assert_eq!(mermaid(&m), mermaid(&m));
    }
}
